# Generated by Django 5.1.1 on 2024-09-13 20:04

import django.db.models.deletion
import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[usuarios.models.validar_cpf])),
                ('data_nasc', models.DateField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='icones')),
                ('senha', models.CharField(blank=True, max_length=6, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('funcao_atual', models.CharField(max_length=30)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('historico_funcoes', models.TextField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='usuarios.colaborador')),
            ],
        ),
    ]
